spring:
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 50MB #限制文件上传大小为10M


mybatis:
  mapper-locations:
     - classpath:mapper/*.xml
     - classpath*:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8888
  servlet:
    context-path: /gateway
  address: 0.0.0.0
logging:
  file:
    path: C:\serverAppLogs
